 export const ADD_TODO='ADD_TODO'
 export const ADD_TODO_FAIL='ADD_TODO_FAIL'
 export const REMOVE_TODO='REMOVE_TODO'
 export const REMOVE_TODO_FAIL='REMOVE_TODO_FAIL'
 export const UPDATE_TODO='UPDATE_TODO'
 export const UPDATE_TODO_FAIL='UPDATE_TODO_FAIL'
 export const REGISTER_DONE='REGISTER_DONE'
 export const REGISTER_FAIL='REGISTER_FAIL'
 export const LOGIN_DONE='LOGIN_DONE'
 export const LOGIN_FAIL='LOGIN_FAIL'
 export const LOGOUT_DONE='LOGOUT_DONE'
 export const LOGUUT_FAIL='LOGUUT_FAIL'
 export const UPDATE_USER_INFO='UPDATE_USER_INFO'
 export const UPDATE_USER_FAIL='UPDATE_USER_FAIL'
 export const GET_TODOS='GET_TODOS'
 export const GET_TODOS_FAIL='GET_TODOS_FAIL'
 export const GET_SINGLE_TODO='GET_SINGLE_TODO'
 export const SET_FAV_TODO='SET_FAV_TODO'
 export const SET_FAV_TODO_FAIL='SET_FAV_TODO_FAIL'
 export const GET_FAV_TODOS='GET_FAV_TODOS'
 export const GET_FAV_TODOS_FAIL='GET_FAV_TODOS_FAIL'
 export const GET_SINGLE_TODO_FAIL='GET_SINGLE_TODO_FAIL'
 export const DARK_MODE='DARK_MODE'
 export const SESSION_EXPIRED='SESSION_EXPIRED'
 
export const SET_OPEN_MODAL = 'SET_OPEN_MODAL';
export const SET_CLOSE_MODAL = 'SET_CLOSE_MODAL';


